# Generated by Django 5.2.10 on 2026-01-28 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(help_text='Первый день месяца')),
                ('quality', models.FloatField(help_text='Качество %')),
                ('breaks_pct', models.FloatField(help_text='% перерывов')),
                ('cvd', models.FloatField(help_text='CVD показатель')),
                ('hold_pct', models.FloatField(help_text='HOLD %')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Метрики сотрудника',
                'verbose_name_plural': 'Метрики сотрудников',
                'unique_together': {('employee', 'period')},
            },
        ),
    ]
